### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [ozanerturk/covid19-turkey-api#23]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/NVC9MY
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by ozanerturk** [comment]
Hi, that is great!.  Sure I will check what should I do about "Dataverse" because I do not know this well. and will raise this issue if anyone would like to give a hand for metadata updates.

**Comment by ozanerturk** [comment]
@hbayindir, we had a small talk about licensing the dataset I guess you could have some ideas on this topic too. Could you share your comment?

**Comment by ozanerturk** [comment]
> Hello,
> Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/NVC9MY
> Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

First think I notice when I check the link is there are 2 false file attached as dataset.
![image](https://user-images.githubusercontent.com/15703627/87157175-8346f480-c2c6-11ea-93ef-749e24cca6d2.png)

package.json and package-lock.json are not dataset files.
dataset files are "timeline.csv" and "timeline.json"
These data sets are updated every day automatically.

**Comment by hbayindir** [comment]
> @hbayindir, we had a small talk about licensing the dataset I guess you could have some ideas on this topic too. Could you share your comment?

I actually have some knowledge about open data and its licensing. I'll take a look it in the weekend. Maybe we can setup something automated so it shifts the burden to the machines.

**Comment by hbayindir** [comment]
@reeshmabijosh,

I've created an account in your Dataverse installation but, adding more data links fail due to some problems. Also, to update the data one needs to be able to claim the data so it can be updated with correct metadata and versioning.

@ozanerturk,
For the data license, a Creative Commons BY-SA 4.0 license will do the trick. It's similar to the MIT license and states the following:

- Credit must be given to you, the creator. 
- Adaptations must be shared under the same terms.

So, people can use the data and build upon it, including commercial usage. However, the resulting data should be shared with the same license, and you must be credited for your part. If you want a different license, you can create one from [CreativeCommons License Chooser](https://chooser-beta.creativecommons.org/) and re-license your data.

For the dataverse side, looks like it allows API (REST) based interactions, so the data can be updated automatically but, the API token should be kept safe. I don't remember whether GitHub provides this feature or not.

**Comment by ozanerturk** [comment]
@hbayindir thanks a lot for your effort. For the license part, Maybe we should go more open to use  license which is not requiring a credit at all. That would be great if you can fork and add a proper license then make a pull request.

@reeshmabijosh with @hbayindir's comment I also checked your platform and could not figure it out how to use it. Can you show us the way what we should do precisely.

Thank you guys.

**Comment by hbayindir** [comment]
@ozanerturk 
You're welcome. So, to clarify, you want a license:
- Requires no referencing to use the data and,
- Which can be used commercially.

Do you wish that the license perpetuates with all other work, or you just like a *data version* of the current MIT license?

Just wanted to ask because I believe in "measure twice, cut once" approach. :)

**Comment by ozanerturk** [comment]
Yes, that is exactly what I think. _" data version of the current MIT license"_ this summarizes well

**Comment by hbayindir** [comment]
@ozanerturk, I've forked and started to work. I'll send the PR as soon as I can finish the changes.
